Repository mongodb/docs-bi-connector, pull requests merged in 2019-01, with the labels that each got.

#203 DOCSP-3983 - BIC 2.9.0 Release Notes
  source/release-notes.txt
Labels: tech review

#201 (DOCSP-3557) Document how to connect Atlas BIConnector to Looker
  source/client-applications.txt
  source/connect/looker.txt
  source/images/bi-connector/cards/looker-card.png
  source/images/bi-connector/looker-connection-settings.png
  source/includes/steps-connect-looker.yaml
Labels: copy review

#206 DOCSP-3526: [BIC] Support GROUP_CONCAT aggregate function
  source/index.txt
  source/reference.txt
  source/supported-operations.txt
Labels: copy review

#210 (DOCSP-1089): Added known issue on GROUP BY.
  source/reference/known-issues.txt
  source/release-notes.txt
Labels: rfm
