Repository mongodb/docs-bi-connector, pull requests merged in 2019-02, with the labels that each got.

#212 (DOCS-12418): Add sudo to system service commands.
  source/launch.txt
Labels: rfm

#213 (DOCSP-4251): Fixed Supported Platforms.
  source/installation.txt
Labels: copy review, tech review

#214 DOCSP-4549: [BIC] SSL description references MySQL Server
  source/includes/options-mongosqld.yaml
Labels: tech review

#205 (DOCSP-3631) (DOCSP-3677) Document environment variables for BIC
  source/includes/fact-system-vars.rst
  source/includes/toc-reference-landing.yaml
  source/reference.txt
  source/reference/system-variables.txt
  source/reference/user-authorization.txt
Labels: tech review
